// ============================================================
// CostFlow — Domain Presets (5 Industries)
// ============================================================
import type { DomainPreset } from "@/types/costing";

const v = (id: string, name: string, value: number, unit?: string, description?: string) => ({
  id, name, value, unit, description,
});

export const DOMAIN_PRESETS: DomainPreset[] = [
  {
    id: "manufacturing",
    label: "Manufacturing & Fabrication",
    description: "BOM-based costing: raw material density, Kg→Meter conversions, scrap %, machine shift rates",
    icon: "Factory",
    color: "#3B82F6",
    gradient: "from-blue-600 to-cyan-500",
    defaultCurrency: "INR",
    unitSystem: "metric",
    blocks: [
      {
        type: "raw_material", label: "Raw Material Cost", enabled: true, order: 0,
        color: "#3B82F6", icon: "Package",
        description: "Material cost: qty × unit cost",
        formula: "qty * unitCost",
        excelFormula: "=B{r}*C{r}",
        variables: [
          v("qty", "Quantity (Kg)", 50, "Kg", "Raw material quantity"),
          v("unitCost", "Unit Cost (₹/Kg)", 120, "₹/Kg"),
        ],
      },
      {
        type: "wastage", label: "Scrap & Wastage", enabled: true, order: 1,
        color: "#F59E0B", icon: "Trash2",
        description: "Scrap rate × material cost",
        formula: "materialCost * scrapPct",
        excelFormula: "=D{r}*E{r}",
        variables: [v("scrapPct", "Scrap Rate %", 0.08, "%")],
      },
      {
        type: "direct_labor", label: "Direct Labor", enabled: true, order: 2,
        color: "#10B981", icon: "Users",
        description: "Labor hours × hourly rate × workers",
        formula: "laborHours * hourlyRate * workers",
        excelFormula: "=F{r}*G{r}*H{r}",
        variables: [
          v("laborHours", "Labor Hours", 8, "hrs"),
          v("hourlyRate", "Hourly Rate (₹)", 85, "₹/hr"),
          v("workers", "Workers", 3, "persons"),
        ],
      },
      {
        type: "variable_overhead", label: "Machine Wear & Power", enabled: true, order: 3,
        color: "#8B5CF6", icon: "Settings",
        description: "Machine rate × shift hours + power cost",
        formula: "machineRate * shiftHours + powerCost",
        excelFormula: "=I{r}*J{r}+K{r}",
        variables: [
          v("machineRate", "Machine Rate (₹/hr)", 200, "₹/hr"),
          v("shiftHours", "Shift Hours", 8, "hrs"),
          v("powerCost", "Power Cost (₹)", 350, "₹"),
        ],
      },
      {
        type: "finishing", label: "Surface Finishing", enabled: true, order: 4,
        color: "#EC4899", icon: "Sparkles",
        description: "Length in meters × finishing cost/meter",
        formula: "lengthMeters * finishCostPerMeter",
        excelFormula: "=L{r}*M{r}",
        variables: [
          v("lengthMeters", "Length (m)", 25, "m"),
          v("finishCostPerMeter", "Finish Cost (₹/m)", 45, "₹/m"),
        ],
      },
      {
        type: "tax_gst", label: "GST / Tax", enabled: true, order: 5,
        color: "#EF4444", icon: "Receipt",
        description: "GST on subtotal",
        formula: "subtotal * gstRate",
        excelFormula: "=N{r}*O{r}",
        variables: [v("gstRate", "GST Rate %", 0.18, "%")],
      },
      {
        type: "profit_markup", label: "Profit Markup", enabled: true, order: 6,
        color: "#06B6D4", icon: "TrendingUp",
        description: "Profit margin on total cost",
        formula: "totalCost * markupPct",
        excelFormula: "=P{r}*Q{r}",
        variables: [v("markupPct", "Markup %", 0.25, "%")],
      },
    ],
  },
  {
    id: "school",
    label: "Education — School / College",
    description: "Per-student overhead: classroom allocation, teacher rates, lab fees, bus transport",
    icon: "GraduationCap",
    color: "#8B5CF6",
    gradient: "from-purple-600 to-pink-500",
    defaultCurrency: "INR",
    unitSystem: "metric",
    blocks: [
      {
        type: "fixed_overhead", label: "Classroom Overhead", enabled: true, order: 0,
        color: "#8B5CF6", icon: "School",
        description: "(Rent + utilities) ÷ students",
        formula: "(rentMonthly + utilities) / studentsPerClass",
        excelFormula: "=(B{r}+C{r})/D{r}",
        variables: [
          v("rentMonthly", "Classroom Rent (₹/mo)", 25000, "₹/mo"),
          v("utilities", "Utilities (₹/mo)", 5000, "₹/mo"),
          v("studentsPerClass", "Students/Class", 40, "students"),
        ],
      },
      {
        type: "direct_labor", label: "Teacher / Faculty Cost", enabled: true, order: 1,
        color: "#10B981", icon: "BookOpen",
        description: "(Salary × count) ÷ total students",
        formula: "(teacherSalary * teacherCount) / totalStudents",
        excelFormula: "=(E{r}*F{r})/G{r}",
        variables: [
          v("teacherSalary", "Teacher Salary (₹/mo)", 45000, "₹/mo"),
          v("teacherCount", "Teacher Count", 8, "persons"),
          v("totalStudents", "Total Students", 320, "students"),
        ],
      },
      {
        type: "variable_overhead", label: "Lab & Equipment Fee", enabled: true, order: 2,
        color: "#F59E0B", icon: "FlaskConical",
        description: "Lab cost ÷ students per lab",
        formula: "labEquipmentCost / studentsPerLab",
        excelFormula: "=H{r}/I{r}",
        variables: [
          v("labEquipmentCost", "Lab Equipment (₹/mo)", 18000, "₹/mo"),
          v("studentsPerLab", "Students/Lab", 30, "students"),
        ],
      },
      {
        type: "transport", label: "Bus Transport", enabled: true, order: 3,
        color: "#3B82F6", icon: "Bus",
        description: "(Fuel + driver + maintenance) ÷ bus students",
        formula: "(busFuelCost + driverSalary + maintenance) / busStudents",
        excelFormula: "=(J{r}+K{r}+L{r})/M{r}",
        variables: [
          v("busFuelCost", "Fuel Cost (₹/mo)", 12000, "₹/mo"),
          v("driverSalary", "Driver Salary (₹/mo)", 18000, "₹/mo"),
          v("maintenance", "Maintenance (₹/mo)", 4000, "₹/mo"),
          v("busStudents", "Students on Bus", 45, "students"),
        ],
      },
      {
        type: "profit_markup", label: "Admin & Surplus", enabled: true, order: 4,
        color: "#06B6D4", icon: "Building2",
        description: "Admin overhead %",
        formula: "totalCost * adminPct",
        excelFormula: "=N{r}*O{r}",
        variables: [v("adminPct", "Admin Overhead %", 0.15, "%")],
      },
    ],
  },
  {
    id: "retail",
    label: "Retail & Kirana Store",
    description: "Landed cost, wastage %, volume markup, multi-pack discount, GST",
    icon: "ShoppingCart",
    color: "#10B981",
    gradient: "from-emerald-600 to-teal-500",
    defaultCurrency: "INR",
    unitSystem: "metric",
    blocks: [
      {
        type: "raw_material", label: "Landed Purchase Cost", enabled: true, order: 0,
        color: "#10B981", icon: "Truck",
        description: "Purchase price + transport cost",
        formula: "purchasePrice + transportCost",
        excelFormula: "=B{r}+C{r}",
        variables: [
          v("purchasePrice", "Purchase Price (₹/Kg)", 80, "₹/Kg"),
          v("transportCost", "Transport Cost (₹/Kg)", 8, "₹/Kg"),
        ],
      },
      {
        type: "wastage", label: "Spoilage & Wastage", enabled: true, order: 1,
        color: "#F59E0B", icon: "AlertTriangle",
        description: "Landed cost × spoilage %",
        formula: "landedCost * spoilagePct",
        excelFormula: "=D{r}*E{r}",
        variables: [v("spoilagePct", "Spoilage Rate %", 0.05, "%")],
      },
      {
        type: "fixed_overhead", label: "Store Overhead", enabled: true, order: 2,
        color: "#8B5CF6", icon: "Store",
        description: "(Rent + electricity + staff) ÷ monthly Kg sold",
        formula: "(storeRent + electricity + staffCost) / monthlyKgSold",
        excelFormula: "=(F{r}+G{r}+H{r})/I{r}",
        variables: [
          v("storeRent", "Store Rent (₹/mo)", 20000, "₹/mo"),
          v("electricity", "Electricity (₹/mo)", 3500, "₹/mo"),
          v("staffCost", "Staff Cost (₹/mo)", 15000, "₹/mo"),
          v("monthlyKgSold", "Monthly Kg Sold", 2000, "Kg"),
        ],
      },
      {
        type: "profit_markup", label: "Retail Margin", enabled: true, order: 3,
        color: "#06B6D4", icon: "TrendingUp",
        description: "Gross profit margin",
        formula: "totalCost * markupPct",
        excelFormula: "=J{r}*K{r}",
        variables: [v("markupPct", "Markup %", 0.30, "%")],
      },
      {
        type: "tax_gst", label: "GST", enabled: true, order: 4,
        color: "#EF4444", icon: "Receipt",
        description: "GST on selling price",
        formula: "subtotal * gstRate",
        excelFormula: "=L{r}*M{r}",
        variables: [v("gstRate", "GST Rate %", 0.05, "%")],
      },
    ],
  },
  {
    id: "ecommerce",
    label: "E-Commerce & D2C",
    description: "COGS, gateway %, shipping tiers, CAC buffer, return rate provisioning",
    icon: "Globe",
    color: "#F59E0B",
    gradient: "from-amber-500 to-orange-500",
    defaultCurrency: "INR",
    unitSystem: "metric",
    blocks: [
      {
        type: "raw_material", label: "Product / COGS", enabled: true, order: 0,
        color: "#F59E0B", icon: "Box",
        description: "Cost of goods per unit",
        formula: "cogsCost",
        excelFormula: "=B{r}",
        variables: [v("cogsCost", "COGS per Unit (₹)", 250, "₹")],
      },
      {
        type: "packaging", label: "Packaging Cost", enabled: true, order: 1,
        color: "#06B6D4", icon: "Package",
        description: "Box + bubble wrap + tape per order",
        formula: "packagingCost",
        excelFormula: "=C{r}",
        variables: [v("packagingCost", "Packaging (₹)", 35, "₹")],
      },
      {
        type: "transport", label: "Shipping & Fulfillment", enabled: true, order: 2,
        color: "#3B82F6", icon: "Plane",
        description: "Base + (weight × rate/Kg)",
        formula: "shippingBase + (weightKg * shippingPerKg)",
        excelFormula: "=D{r}+(E{r}*F{r})",
        variables: [
          v("shippingBase", "Base Shipping (₹)", 60, "₹"),
          v("weightKg", "Product Weight (Kg)", 0.5, "Kg"),
          v("shippingPerKg", "Per Kg Rate (₹)", 30, "₹/Kg"),
        ],
      },
      {
        type: "variable_overhead", label: "Payment Gateway %", enabled: true, order: 3,
        color: "#8B5CF6", icon: "CreditCard",
        description: "Gateway fee on selling price",
        formula: "sellingPrice * gatewayPct",
        excelFormula: "=G{r}*H{r}",
        variables: [v("gatewayPct", "Gateway Fee %", 0.02, "%")],
      },
      {
        type: "wastage", label: "Return Buffer", enabled: true, order: 4,
        color: "#EF4444", icon: "RotateCcw",
        description: "Return rate × reverse logistics cost",
        formula: "returnRate * returnLogisticsCost",
        excelFormula: "=I{r}*J{r}",
        variables: [
          v("returnRate", "Return Rate %", 0.08, "%"),
          v("returnLogisticsCost", "Return Logistics (₹)", 80, "₹"),
        ],
      },
      {
        type: "fixed_overhead", label: "CAC Buffer", enabled: true, order: 5,
        color: "#10B981", icon: "Target",
        description: "Customer Acquisition Cost per order",
        formula: "cac",
        excelFormula: "=K{r}",
        variables: [v("cac", "CAC per Order (₹)", 120, "₹")],
      },
      {
        type: "profit_markup", label: "D2C Margin", enabled: true, order: 6,
        color: "#F59E0B", icon: "TrendingUp",
        description: "Target margin %",
        formula: "totalCost * markupPct",
        excelFormula: "=L{r}*M{r}",
        variables: [v("markupPct", "Margin %", 0.35, "%")],
      },
    ],
  },
  {
    id: "construction",
    label: "Construction & Metals",
    description: "Area metrics (sq ft/m²), linear meters, subcontract, fabrication labor, yield loss",
    icon: "HardHat",
    color: "#EF4444",
    gradient: "from-red-600 to-rose-500",
    defaultCurrency: "INR",
    unitSystem: "metric",
    blocks: [
      {
        type: "raw_material", label: "Material Cost (Area)", enabled: true, order: 0,
        color: "#EF4444", icon: "Layers",
        description: "sq.m × cost/sq.m",
        formula: "areaSqm * materialCostPerSqm",
        excelFormula: "=B{r}*C{r}",
        variables: [
          v("areaSqm", "Area (sq.m)", 500, "sq.m"),
          v("materialCostPerSqm", "Material Cost (₹/sq.m)", 850, "₹/sq.m"),
        ],
      },
      {
        type: "wastage", label: "Material Yield Loss", enabled: true, order: 1,
        color: "#F59E0B", icon: "AlertTriangle",
        description: "Material cost × yield loss %",
        formula: "materialCost * yieldLossPct",
        excelFormula: "=D{r}*E{r}",
        variables: [v("yieldLossPct", "Yield Loss %", 0.10, "%")],
      },
      {
        type: "direct_labor", label: "Fabrication Labor", enabled: true, order: 2,
        color: "#10B981", icon: "Hammer",
        description: "sq.m × labor cost/sq.m",
        formula: "areaSqm * laborCostPerSqm",
        excelFormula: "=F{r}*G{r}",
        variables: [v("laborCostPerSqm", "Labor Cost (₹/sq.m)", 220, "₹/sq.m")],
      },
      {
        type: "variable_overhead", label: "Subcontract Work", enabled: true, order: 3,
        color: "#8B5CF6", icon: "Wrench",
        description: "Third-party charges",
        formula: "subcontractAmount",
        excelFormula: "=H{r}",
        variables: [v("subcontractAmount", "Subcontract (₹)", 75000, "₹")],
      },
      {
        type: "fixed_overhead", label: "Site Overhead", enabled: true, order: 4,
        color: "#3B82F6", icon: "Building",
        description: "Site management + equipment rental",
        formula: "siteOverhead",
        excelFormula: "=I{r}",
        variables: [v("siteOverhead", "Site Overhead (₹)", 45000, "₹")],
      },
      {
        type: "tax_gst", label: "GST on Works Contract", enabled: true, order: 5,
        color: "#EF4444", icon: "Receipt",
        description: "12% GST on works contracts",
        formula: "subtotal * gstRate",
        excelFormula: "=J{r}*K{r}",
        variables: [v("gstRate", "GST Rate %", 0.12, "%")],
      },
      {
        type: "profit_markup", label: "Contractor Margin", enabled: true, order: 6,
        color: "#06B6D4", icon: "TrendingUp",
        description: "Contractor profit margin",
        formula: "totalCost * markupPct",
        excelFormula: "=L{r}*M{r}",
        variables: [v("markupPct", "Contractor Margin %", 0.20, "%")],
      },
    ],
  },
];

export function getPreset(domain: string): DomainPreset | undefined {
  return DOMAIN_PRESETS.find((p) => p.id === domain);
}
